######################################################################
# Automatically generated by qmake (3.0) Tue Aug 16 19:58:11 2016
######################################################################

TEMPLATE = app
TARGET = attr
QT			+= xml
INCLUDEPATH += . AttrRecognize AttrRecognize/AttrBase \
	/usr/local/opencv3/include \
	/usr/local/opencv3/include/opencv \
	/usr/local/opencv3/include/opencv2
	LIBS += -L /usr/local/opencv3/lib/ \
	/usr/local/opencv3/lib/libopencv_highgui.so \
	/usr/local/opencv3/lib/libopencv_core.so \
	/usr/local/opencv3/lib/libopencv_imgproc.so \
	/usr/local/opencv3/lib/libopencv_imgcodecs.so \
	/usr/local/opencv3/lib/libopencv_ml.so \
	/usr/local/opencv3/lib/libopencv_objdetect.so \
	/usr/local/opencv3/lib/libopencv_ximgproc.so \
	/var/www/html/myWeb/WebExe/vlfeat-0.9.20/bin/glnxa64/libvl.so
	
# Input
HEADERS += reference.h \
           reference/buildAttrRelation.h \
           reference/AttrBase/cvTool.h \
           reference/AttrBase/myfunc_base.h \
           reference/AttrBase/planimetry_tools.h \
           reference/AttrBase/svm.h \
           reference/AttrBase/svmpredict.h \
           reference/AttrRecognize/attrRecognize.h \
           reference/AttrRecognize/hist2DTool.h \
           reference/AttrRecognize/imagesp.h \
           reference/AttrRecognize/mylocation.h \
           reference/AttrRecognize/ScaleTool.h \
           reference/AttrRecognize/skincoloranalyze.h \
           reference/AttrRecognize/skinmodel.h \
           reference/AttrRecognize/sleeveHeader.h \
           reference/SysConfig/attrconfigdata.h \
           reference/SysConfig/defination.h \
           reference/SysConfig/poseconfigdata.h
SOURCES += attrGet.cpp \
           reference/buildAttrRelation.cpp \
           reference/AttrBase/myfunc_base.cpp \
           reference/AttrBase/planimetry_tools.cpp \
           reference/AttrBase/svm.cpp \
           reference/AttrBase/svmpredict.cpp \
           reference/AttrRecognize/attrAllBase.cpp \
           reference/AttrRecognize/collar.cpp \
           reference/AttrRecognize/collarWay2.cpp \
           reference/AttrRecognize/color.cpp \
           reference/AttrRecognize/extraColor.cpp \
           reference/AttrRecognize/imagesp.cpp \
           reference/AttrRecognize/layout.cpp \
           reference/AttrRecognize/mylocation.cpp \
           reference/AttrRecognize/skincoloranalyze.cpp \
           reference/AttrRecognize/skinmodel.cpp \
           reference/AttrRecognize/sleeve.cpp \
           reference/AttrRecognize/sleeveHeader.cpp \
           reference/AttrRecognize/sleeveWay2.cpp \
           reference/AttrRecognize/sleeveWay3.cpp \
           reference/AttrRecognize/sleeveWay4.cpp \
           reference/AttrRecognize/texture.cpp \
           reference/AttrRecognize/uplength.cpp \
           reference/AttrRecognize/uplength2.cpp
RESOURCES += reference/cfgFile/files.qrc
